version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./workoutplans:/app/workoutplans
    command: python3 workoutplans/manage.py runserver 0.0.0.0:8000
